import enum


class CommandUtils:
    class Agents(enum.Enum):
        Brimstone = "Brimstone"
        Viper = "Viper"
        Omen = "Omen"
        Killjoy = "Killjoy"
        Cypher = "Cypher"
        Sova = "Sova"
        Sage = "Sage"
        Phoenix = "Phoenix"
        Jett = "Jett"
        Reyna = "Reyna"
        Raze = "Raze"
        Breach = "Breach"
        Skye = "Skye"
        Yoru = "Yoru"
        Astra = "Astra"
        KAYO = "KAY/O"
        Chamber = "Chamber"
        Neon = "Neon"
        Fade = "Fade"
        Harbor = "Harbor"
        Gekko = "Gekko"
        Deadlock = "Deadlock"
        Iso = "Iso"
        Clove = "Clove"

    class Maps(enum.Enum):
        Bind = "Bind"
        Haven = "Haven"
        Split = "Split"
        Ascent = "Ascent"
        Icebox = "Icebox"
        Breeze = "Breeze"
        Fracture = "Fracture"
        Pearl = "Pearl"
        Lotus = "Lotus"
        Sunset = "Sunset"

    class Ranks(enum.Enum):
        Iron_1 = "Iron 1"
        Iron_2 = "Iron 2"
        Iron_3 = "Iron 3"
        Bronze_1 = "Bronze 1"
        Bronze_2 = "Bronze 2"
        Bronze_3 = "Bronze 3"
        Silver_1 = "Silver 1"
        Silver_2 = "Silver 2"
        Silver_3 = "Silver 3"
        Gold_1 = "Gold 1"
        Gold_2 = "Gold 2"
        Gold_3 = "Gold 3"
        Platinum_1 = "Platinum 1"
        Platinum_2 = "Platinum 2"
        Platinum_3 = "Platinum 3"
        Diamond_1 = "Diamond 1"
        Diamond_2 = "Diamond 2"
        Diamond_3 = "Diamond 3"
        Ascendant_1 = "Ascendant 1"
        Ascendant_2 = "Ascendant 2"
        Ascendant_3 = "Ascendant 3"
        Immortal_1 = "Immortal 1"
        Immortal_2 = "Immortal 2"
        Immortal_3 = "Immortal 3"
        Radiant = "Radiant"
