name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Black formatting changes
